app/models.py
from app import db

class Task(db.Model):
    __tablename__ = 'task'
    id_task = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombre = db.Column(db.String(80), nullable=False)
    estado = db.Column(db.SMALLINT, nullable=False)

    def __repr__(self):
        return f'<Tarea {self.nombre}>'

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    app.config.from_object('config.Config')
    
    db.init_app(app)
    
    from .routes.main import main
    from .routes.crud import crud
    app.register_blueprint(main)
    app.register_blueprint(crud)
    
    return app

app/routes/crud.py
from flask import Blueprint, render_template, redirect, url_for, request, jsonify
from app import db
from app.models import Task

crud = Blueprint('crud', __name__)

@crud.route('/agregar-task', methods=['GET', 'POST'])
def agregarTask():
    if request.method == 'POST':
        
        task = Task(
            nombre=request.form['nombre'],
            estado=1
        )

        db.session.add(task)
        db.session.commit()
    return redirect(url_for('main.index'))

@crud.route('/toggle-task/<int:id_task>', methods=['POST'])
def toggleTask(id_task):
    task = Task.query.get_or_404(id_task)

    if task.estado == 1:
        task.estado = 0
    else:
        task.estado = 1

    db.session.commit()

    return redirect(url_for('main.index'))

@crud.route('/eliminar-task/<int:task_id>', methods=['POST'])
def eliminar_tarea(task_id):
    try:
        tarea = Task.query.get(task_id)
        if tarea:
            db.session.delete(tarea)
            db.session.commit()
            return jsonify({'message': 'Tarea eliminada correctamente'}), 200
        else:
            return jsonify({'error': 'No se encontró la tarea'}), 404
    except Exception as e:
        return jsonify({'error': str(e)}), 500

app/routes/main.py
from flask import Blueprint, render_template
from app.models import Task

main = Blueprint('main', __name__)

@main.route('/')
def index():
    tasks = Task.query.order_by(Task.estado.desc()).all()
    return render_template('index.html', tasks=tasks)

app/templates/base.html
<!-- base.html -->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block titulo %}{% endblock  %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/estilo.css')}}">
    <link href="https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap" rel="stylesheet">
    {% block head %}{% endblock %}
    <link rel="shortcut icon" href="{{ url_for('static', filename='images/logo.jpg') }}" type="image/x-icon">
</head>
<body>
    <header>

    </header>

    <!-- CONTENIDO MAIN -->
    <main>
        {% block main %}
        {% endblock %}
    </main>

    <footer>
        
    </footer>

    <!-- CONTENIDO SCRIPTS -->
    {% block scripts %}
    {% endblock %}
    
</body>
</html>

app/templates/index.html
{% extends 'base.html' %}
{% block titulo %} Tareas {% endblock titulo %}
{% block main %}
    <div class="content-list">
        <div class="titulo">
            {% if tasks | length >= 2 %}
                <h1>Lista de Tareas</h1>
            {% else %}
                <h1>Tarea</h1>
            {% endif %}
        </div>
        {% if tasks %}
        <div class="tareas">
            {% for task in tasks %}
            <div class="tarea">
                <div class="nombre-tarea">
                    <p data-task-id="{{ task.id_task }}" {% if task.estado != 1 %} style="text-decoration: line-through;" {% endif %}>{{ task.nombre }}</p>
                    <button class="btn-eliminar" data-task-id="{{ task.id_task }}">Eliminar</button>
                </div>
                <div class="estado">
                    <input type="checkbox" name="estado" id="estado-{{ task.id_task }}" data-task-id="{{ task.id_task }}" {% if task.estado == 1 %} checked {% endif %}>
                </div>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        <!-- Formulario para agregar tarea (inicialmente oculto) -->
        <div class="formulario-agregar" id="formularioAgregar" style="display: none;">
            <form action="{{ url_for('crud.agregarTask') }}" method="POST">
                <input type="text" name="nombre" placeholder="Nombre de la tarea" required>
                <button type="submit">Agregar</button>
            </form>
        </div>
        <div class="boton">
            <button type="button" id="btnAgregar">+</button>
        </div>
    </div>
{% endblock main %}
{% block scripts %}
<script src="{{ url_for('static', filename='js/cambiarTaks.js') }}"></script>
<script src="{{ url_for('static', filename='js/botones.js') }}"></script>
{% endblock scripts %}